---
- name: Update APT and install packages
  hosts: devel
  become: yes
  tasks:
   - name: apt update && apt install
#     apt: package={{ item }} update_cache=yes
#     with_items:
     apt:
      pkg:
       - git
       - maven
       - tomcat8
       - python
      update_cache: yes

- name: build package
  hosts: devel
  become: yes
  tasks:
   - name: download test package from github
     git:
      repo: https://github.com/doct15/example-tomcat-war.git
#      clone: yes
      dest: /root/repo
   - name: build package with maven
     command:
      chdir: /root/repo
      cmd: mvn package
   - name: copy artefact to tomcat dir
     command:
      cmd: mv /root/repo/target/SimpleTomcatWebApp.war
           /var/lib/tomcat8/webapps
     notify:
       - restart tomcat8
  handlers:
   - name: restart tomcat8
     service:
      name: tomcat8
      state: restarted
